use_gpu: true
use_xpu: false
use_mlu: false
use_npu: false
log_iter: 20
save_dir: output/AIC2026_QADepth
snapshot_epoch: 1
print_flops: false
print_params: false

export:
  post_process: True
  nms: True
  benchmark: False
  fuse_conv_bn: False
